
public enum ESandboxObjectiveType
{
    None = -1,
    DestroyBase,
    DestroyMultipleBases,
    SeekAndDestroy,
    SeekAndDestroyMultiple,
    DestroyTimedFleets,
    DestroyChase,
    DestroyChaseMultiple,
    RetrieveTimedPlanes,
    RetrieveTimedSurvivors,
    RetrieveSurvivorsUnknown,
    DefendBase,
    DefendMultipleBases,
    DefendFleet,
    DefendMultipleFleets,
    DefendAllyTimed,
    EscortRetreat,
    EscortAttack,
    EscortInvasion,
    DestroyFleetUndetected,
    DefendBaseUndetected,
    DefendFleetUndetected,
    Scout,
    ScoutBase,
    Patrol,
    PatrolBase,
    PatrolUndetected,
    UndetectedPatrolBase,
    EnemyFleetInstance,
    Count
}
