using System;

[Flags]
public enum ETutorialMode
{
    DisableIslandViewSwitch             = 1 <<  0,
    DisableDeckViewSwitch               = 1 <<  1,
    DisableSectionsViewSwitch           = 1 <<  2,
    DisableFreeViewSwitch               = 1 <<  3,
    DisableOfficers                     = 1 <<  4,
    DisableDC                           = 1 <<  5,
    DisableCameraControls               = 1 <<  6,
    DisableOtherDCIdle                  = 1 <<  7,
    DisableFreeSectionSelection         = 1 <<  8,
    DisableFreeWaypointSet              = 1 <<  9,
    DisableAttack                       = 1 << 10,
    DisableMissionRetrieveFailure       = 1 << 11,
    DisableFreeOfficerAssign            = 1 << 12,
    DisableAssignOfficerToCIC           = 1 << 13,
    DisableCrewDrag                     = 1 << 14,
    DisableFreeCrewDrag                 = 1 << 15,
    DisableFleetDisappearance           = 1 << 16,
    DisableFreeFleetIdentification      = 1 << 17,
    DisableMissionSet                   = 1 << 18,
    DisableRandomMissionAttackResults   = 1 << 19, 
    DisableDCMoveOutsidePumps           = 1 << 20,
    DisableDCEvents                     = 1 << 21,
    DisableFreeStrategyDrag             = 1 << 22,
    DisableCancelOnTacticalMap          = 1 << 23,
    DisableMissionTimeout               = 1 << 24,
    DisableUsingSupplies                = 1 << 25,
    DisableWrecks                       = 1 << 26, 
    DisableTimeFly                      = 1 << 27,
    DisableMissionButtonStageChange     = 1 << 28,
    DisableViewSwitch                   = DisableDeckViewSwitch | DisableSectionsViewSwitch | DisableIslandViewSwitch | DisableFreeViewSwitch,
    DisableHovers                       = DisableOfficers | DisableDC,
    DisableAllDC                        = DisableDC | DisableOtherDCIdle, 
    DisableAll                          = -1,
}