
public enum EAudio
{
    Generate = -1,
    ObjectiveCompleted,
    ObjectiveFailed,
    Fault,
    Fire,
    Flood,
    Injured,
    NewIntel,
    EnemySpotted,
    Attack,
    SubmarineDetected,
    AllyAttacked,
    Detected,
    ShipSunk,
    OrderExpired,
    NewObjective,
    HealthCritical,
    PlaneCrashed,
    OtherEvent,
    SectionShutdown,
    DeckShutdown,
    AirShutdown,
    MedicalShutdown,
    EngineeringShutdown,
    NavigationShutdown,
    AAShutdown,
    PumpsShutdown,
    MaintenanceShutdown,
}
